### PR TITLE
Creating a location for NB 10 standard distribution AUC. Currently re…

### PR DESCRIPTION
**Pull request by jlahoda**
…directs to NB 9.0 AUC.

### CODE REVIEW

**Comment by jkovalsky** [comment]
@jlahoda , please update the URL to http://netbeans-vm.apache.org/uc/10.0/ It redirects to 9.0 UC at the moment but at least the bundled link will be correct. Once the 10.0 UC will be in place I will update the redirection accordingly. FYI @lkishalmi

**Comment by jlahoda** [comment]
@jkovalsky, @vieiro, done.

FTR, I didn't see a huge problem in the temporary redirect to the 9.0 AUC, esp. given I can't control the settings on netbeans-vm. The sole point here was to create a stable place where the IDE can point to, i.e.:
https://netbeans.apache.org/nb/updates/10.0/updates.xml.gz

**Comment by lkishalmi** [comment]
Thanks!

**Comment by vieiro** [comment]
@jlahoda you'll be merging this when appropriate, right?

**Comment by jlahoda** [comment]
@vieiro, thanks for reminder, done.

**Pull request merged**
