### PR TITLE
Reworded the instructions for "installation"

### PR DESCRIPTION
**Pull request by braiam**
It may not be clear that there's no installation process other than
unzipping for Windows OS.

### CODE REVIEW

**Comment by geertjanw** [comment]
But this would be incorrect. "Windows binary" implies that the ZIP file is for Windows only, which it's not.

**Comment by braiam** [comment]
So, I actually didn't downloaded the zip file until now, and I see what you meant. That's heck of confusing.

When presenting a binary without specifying any particular OS and then an installer for one OS, it confuses (Windows) users because they expect every package to be for an specific OS. Maybe if we degrade the installer and add a note that the installer is only for MacOS and that any OS can use the binaries? I'm having troubles meeting every OS user expectation in the download page since Linux users also expect their own libraries (or just compiling from sources). Does asciidoc allows some kind of guided flow (if/then style)?

**Comment by geertjanw** [comment]
You wrote the other changes to the instructions without downloading the ZIP file described in the changes to those instructions?

**Comment by vieiro** [comment]
No timely response. Closing.

**Pull request closed without merging**
