### PR TITLE
add blog entry (redirect to webarchive)

### PR DESCRIPTION
**Pull request by ebarboni**
place holder for blogs entry just link to web archiva

### CODE REVIEW

**Review by vieiro — COMMENTED** [review]
Maybe @geertjanw and Tim, as original authors of the blog entires, are better suited to approve this PR.

**Comment by ebarboni** [comment]
cannot put @timboudreau in reviewer list. 
this are just redirect to web archive . We may later copy paste if we want. 
But if we don't want it, I will remove them from apidoc.

**Review by mbien — APPROVED** [review]
one is about the history of the tree table the other two are about NetBeans Nodes.

Probably fine to link to them. So +1 from me.

**Comment by ebarboni** [comment]
@mbien, @vieiro after checking there is more @geertjanw blog entry.
I will keep this for reference as it's blog entry used from APIDOC. I will do a PR with all referenced Geertjan blog

**Pull request closed without merging**
