### PR TITLE
[NETBEANS-1867] Tutorial reviews and contributions

### PR DESCRIPTION
**Pull request by vieiro**
- Using ":reviewed: 9+" to mark a tutorial as reviewed.
- Modified the "tutorials.gsp" template to include a note indicating if a tutorial has not been reviewed yet.
- Added /kb/docs/contributing.asciidoc with instructions on how to contribute tutorials.

### CODE REVIEW

**Comment by ebarboni** [comment]
Hi @vieiro, 
I would not use 9+, I would prefer 9,10 for the moment as 9+ may be seen as reviewed for Apache NetBeans (11,12,13......) and that will not be true. Even if the logic is check for null now

**Comment by geertjanw** [comment]
Agree with @ebarboni.

**Comment by geertjanw** [comment]
Although, we may be moving to calendar versioning. I'd recommend not making the reviews release-specific, but maybe have a date, i.e., the date on which a tutorial was last reviewed.

**Comment by vieiro** [comment]
@ebarboni , I think @geertjanw about using dates is probably better, right?

**Comment by ebarboni** [comment]
can be also. Maybe jbake can have a list of released netbeans with associated date so we can do stuff later and we put a date i reviewed meta.

just: If we create a new, we may lost the fact its a new tutorial that was not in netbeans 9

**Comment by geertjanw** [comment]
So far the docs team, in terms of actually working on the content of tutorials, is just me. Once I have fixed them up a bit and made sure they work for me and after integrating them into the NetCAT process, I’m not going to be verifying them again for each release. So, for me, it would make sense to tie a tutorial to the last date it was approved, regardless of the release.

**Comment by ebarboni** [comment]
better a date then.

Any commiter may now help during Tutorial Review, it may extend workforce.

**Comment by vieiro** [comment]
So I'll update this with dates then.

**Comment by vieiro** [comment]
To use this:
- Review again (I'm using `:reviewed: 2019-01-25` in all cases).
- Squash and merge.
- Star adding the ":reviewed:" tag with a proper date in those tutorials that we've reviewed.

**Comment by vieiro** [comment]
So we now have to add "`:reviewed: 2019-MM-dd`" in tutorials to mark them as reviewed, otherwise a note will appear pointing to the contribution page.

**Comment by geertjanw** [comment]
Really excellent!

**Comment by geertjanw** [comment]
Two questions:
1. Are instructions included somewherw about how to create an issue for a tutorial, i.e., you identify a problem, can’t/don’t want to fix it, now where do you go/what do you do to file an issue on a specific tutorial?
2. Can we in addition to NOTE have ISSUE in a tutorial, with a screwdriver image or something, to refer to a specific issue that needs to be solved in relation to a step in the tutorial, i.e., ‘this is how the step should work but be aware there is this specific issue that we’re aware of that needs to be solved’?

**Comment by vieiro** [comment]
Two answers:

1. No instructions currently, but we can update kb/docs/contributing.asciidoc to explain how to open an issue in JIRA for a tutorial. I'd suggest requesting a [TUTORIAL] or [DOC] in the title of the JIRA? Or even better: create a JIRA template for tutorials. As a plus: we have a direct link to edit the page in github, maybe we can have a direct link to open a JIRA ticket as well? Will investigate.

2. Standard admonitions are listed here https://asciidoctor.org/docs/asciidoc-writers-guide/#admonitions we can use WARNING:, for instance, to refer to JIRA tickets. For instance:

`
    WARNING: JIRA link:https://issues.apache.org/jira/browse/NETBEANS-1867[] has to be solved for this tutorial to work
`

**Comment by geertjanw** [comment]
Also, if the :reviewed: tag has been added, would be good to show something visible, like a green checkmark, or some kind of indicator, instead of nothing, which is now the case.

**Comment by vieiro** [comment]
Yep. What about adding a text indicating the date the tutorial was reviewed?

**Comment by geertjanw** [comment]
Yes, a checkmark, or some icon, together with the text -- or, if you prefer, no icon, just the text. I kind of prefer some kind of positive icon like a green checkmark.

**Pull request merged**
