### PR TITLE
Release 10.0

### PR DESCRIPTION
**Pull request by vieiro**
Initial commit with information about the 10.0 release.

### CODE REVIEW

**Comment by vieiro** [comment]
We should add a link to the PPMC vote result thread. I'll do a more thorough review tomorrow. Please see review if I'm missing any important features you want to include.

**Comment by vieiro** [comment]
Laszlo, where are the SHA152 files? I cannot see them at the mirrors, for instance, it's not at http://apache.uvigo.es/incubator/netbeans/incubating-netbeans/incubating-10.0/

**Comment by lkishalmi** [comment]
Well, they are present at the original (one and only) distribution 
directory:

https://dist.apache.org/repos/dist/release/incubator/netbeans/incubating-netbeans/incubating-10.0/

Maybe we shall wait a bit longer to get those synced as well, I try to 
look around other mirrors though.

**Comment by lkishalmi** [comment]
https://www.apache.org/dyn/closer.cgi#backup

Please only use the backup mirrors to download KEYS, PGP and MD5 
sigs/hashes or if no other mirrors are working.

**Comment by vieiro** [comment]
Hi @lkishalmi , I've updated the links. PGP/ASC & SHA512 point to https://www.apache.org/dist/, zip files go through mirrors. Let me know if this is enough for having the links working.

We can fine-tune content later on if you want. If you see any important things please let me know.

**Comment by lkishalmi** [comment]
Just use one of the backup servers to get to the .sha512 and .asc files. Also please remove the development build section. That should not go to the project website, as we shall not encourage users to use development builds. I guess that section is Ok on the Wiki.

**Comment by vieiro** [comment]
@lkishalmi Should be ready now!

**Pull request merged**
