### PR TITLE
Revised documentation for 'editor-coderefrence.asciidoc

### PR DESCRIPTION
**Pull request by JeremyCavanagh**
Hi, I have completed revision and would now like to submit it for review.

### CODE REVIEW

**Comment by vieiro** [comment]
Excellent work! Thanks, @JeremyCavanagh ! @lkishalmi , will you please merge?

**Comment by lkishalmi** [comment]
Merged, then. Thank you for your contribution!

**Comment by geertjanw** [comment]
This URL no longer works: https://netbeans.apache.org/kb/docs/java/editor-codereference.html

Do we know why, must be related to this PR.

**Comment by vieiro** [comment]
There were some blank lines between the title and the document metadata, that avoided asciidoctorj to extract the kind of document we were publishing.

Should be up and running now. Sorry for the delay. This is a great contribution, @JeremyCavanagh. Thanks again!

**Pull request merged**
