### PR TITLE
Creating download page for maven artefacts sources

### PR DESCRIPTION
**Pull request by ebarboni**
Hi, this is a PR intended to put a cgi file that reintepret associated html page to allow mirror selection for download like in this page for Apache Maven 3.6.0
http://maven.apache.org/download.cgi?Preferred=http%3A%2F%2Fwwwftp.ciril.fr%2Fpub%2Fapache%2F

The resulting page will be there but I guess some configuration needs to be set with INFRA
https://netbeans.apache.org/download/maven/index.html

Regards

### CODE REVIEW

**Comment by vieiro** [comment]
Hi @ebarboni 

What about creating a page linking to

https://www.apache.org/dyn/closer.cgi/incubator/netbeans/incubating-netbeans/incubating-10.0/incubating-netbeans-10.0-source.zip

Won't that work? Why is a CGI needed at all?

Thanks,
Antonio

**Comment by ebarboni** [comment]
This would be a fallback but it is common to have this cgi that preselect mirror and update link in the page.

As parent pom is not critical for having  Apache NetBeans to work. I would like to test.

Personnaly I prefer the download links to stay within netbeans.apache.org instead of exiting to apache.org/dyn....

Regards
Eric

**Comment by vieiro** [comment]
I see. I'm not sure our web server is able to run cgi scripts, though. Maybe we can double-check with infra.
Or maybe you can merge it and see if this runs ok. I'm afraid I won't be of much help during this week :-(

**Comment by ebarboni** [comment]
I try a merge. If nothing work I ask Infra.

**Comment by ebarboni** [comment]
I works but I need to rediret index.html to index.cgi on this particular folder

**Pull request merged**
