### PR TITLE
Hopefully corrected formatting

### PR DESCRIPTION
**Pull request by JeremyCavanagh**
This includes several minor changes, but I'm not sure if I'm using the right method

### CODE REVIEW

**Comment by geertjanw** [comment]
There appear to be conflicts to be resolved.

**Comment by vieiro** [comment]
Hi Jeremy,

While you were working on your "master" branch in your fork somebody added some stuff to the "master" branch of incubator-netbeans-website.

This happens all the time: you start working on your branch and people keep adding stuff to the master branch of incubator-netbeans-website. When this happens you have to include other people's changes (in incubator-netbeans-website) in your branch first, and then do a pull request.

Your local reposity (i.e., the directory in your hard disk) has a "remote" git repository, this is usually called "origin". In your case this should look like https://github.com/JeremyCavanagh/incubator-netbeans-website.git You can verify this by using the "git remote -v" command.

What we do is tell your hard disk local repository about the Apache incubator-netbeans-website. We do this only once, like so:

    git remote add upstream https://github.com/apache/incubator-netbeans-website.git

Then if you check your remotes again (git remote -v) you'll see that you have two remotes: "origin", pointing to https://github.com/JeremyCavanagh/incubator-netbeans-website.git and "upstream", pointing to https://github.com/apache/incubator-netbeans-website.git.

Now to the point: in order to fetch stuff other people have been doing in incubator-netbeans-website, you do this:

    git fetch upstream 

(this fetches all branches from upstream, i.e., from https://github.com/apache/incubator-netbeans-website.git and stores these branches in a hidden directory in your hard disk)

And then we "merge" these changes with the ones you've been doing in your hard disk (in the branch you're working on):

    git merge upstream/master

Git might complain that there're some changes to the files in your hard disk that are incompatible. This is called a "merge conflict". If so then you have to open the files and review them manually.

Feel free to ask any questions you may have. Some other instructions are available here: http://netbeans.apache.org/participate/submit-pr.html

Cheers,
Antonio

**Comment by JeremyCavanagh** [comment]
Sorry Everyone,
More complete ignorance of how things work. I have run through the changes I made and corrected them. It wasn't someone else Antonio it was 'me', thanks for information very helpful, I'll try not to make any more mistakes, I probably will though.
Regards to one and all
Jeremy

**Comment by geertjanw** [comment]
Thanks for your perseverance! When we merge this, what are the maib changes we should see live in the codereference tutorial?

**Comment by geertjanw** [comment]
Thanks for the great work. Though note the first table seems to cause a big white space above it:

https://netbeans.apache.org/kb/docs/java/editor-codereference.html

**Comment by JeremyCavanagh** [comment]
I had noticed that. The problem is not knowing how the conversion from asciidoc to html is done and how the TOC is inserted.
However, I'm sure the solution is not so difficult and can be revised later. 
 
I have had a quick look at the next two tutorials in the series and think there might be problems.
 
The first, https://netbeans.apache.org/kb/docs/java/code-inspect.html 
 
Investigating what jsr305-2.0.0 is I came a cross this reference: 
https://github.com/google/guava/issues/2960
 
Should I not worry about it and continue with a revision?
 
The second, https://netbeans.apache.org/kb/docs/java/editor-inspect-transform.html
 
The section "Using Configurations" includes references for migrating to JDK5, JDK 7 and JDK 8
 
I also noticed that these are included in NetBeans 10. This seems strange to me, especially as there is no migrate to JDK 11.
 
Again, should I not worry and continue with a revision.
 
Your thoughts would be greatly appreciated.
 
Regards 
 
Jeremy
 
> Message from 23/02/19 15:54 
> From: "Geertjan Wielenga" > To: "apache / incubator-netbeans-website"  > Copy to: "JeremyCavanagh" , "Mention" > Subject: Re: [apache / incubator-netbeans-website] Hopefully corrected formatting (# 319) > >
> Thanks for the great work. Though notes the first table seems to cause a big white space above it:
> https://netbeans.apache.org/kb/docs/java/editor-codereference.html
- You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub , or mute the thread .
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/apache/incubator-netbeans-website","title":"apache/incubator-netbeans-website","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/apache/incubator-netbeans-website"}},"updates":{"snippets":[{"icon":"PERSON","message":"@geertjanw in #319: Thanks for the great work. Though note the first table seems to cause a big white space above it:\r\n\r\nhttps://netbeans.apache.org/kb/docs/java/editor-codereference.html"}],"action":{"name":"View Pull Request","url":"https://github.com/apache/incubator-netbeans-website/pull/319#issuecomment-466658902"}}}[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/apache/incubator-netbeans-website/pull/319#issuecomment-466658902", "url": "https://github.com/apache/incubator-netbeans-website/pull/319#issuecomment-466658902", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by geertjanw** [comment]
In the 2nd, you'll see "Not all releases of the JDK introduce new language features."

Indeed, some people could use Apache NetBeans 10 or 11 to create applications that involve upgrading code from JDK 4 or 5 or whatever.

**Comment by geertjanw** [comment]
That text could be more prominent or larger, whatever you think is best, for this precise reason i.e. others may wonder about the same.

**Pull request merged**
