### PR TITLE
Creating NekoBean's page to netbeans.apache.org

### PR DESCRIPTION
**Pull request by junichi11**
Import from https://ja.netbeans.org/nekobean/

I've also created a Japanese page.
### English page
nekobean_page

### Japanese page
nakobean_page_ja

### CODE REVIEW

**Comment by matthiasblaesing** [comment]
Who owns the artwork? CC-BY is not appropriate for an apache project:

https://www.apache.org/legal/resolved.html#category-b

So could it be relicensed to ALv2?

This is not a critique of the work, just the legal aspect.

**Comment by junichi11** [comment]
@matthiasblaesing 
The author is Kazuko Kaneuchi. 
I know you are familiar with legal issues as you have worked on them so far. So I would like to ask you.

Can't we use these CC BY images at all?
What do we have to do to use them?

If we must change the license, I'll ask Masaki(Oracle) and Kazuko about it.

**Comment by neilcsmith-net** [comment]
@matthiasblaesing out of interest, how do you come to the conclusion we can't use CC-BY from reading the cat-B section?!  It says 

> Software under the following licenses may be included in binary form within an Apache product if the inclusion is appropriately labeled

Not that this is software or CC-BY!  Later in the page it also mentions unmodified media in CC-SA being OK.

Where do the exceptions come from?

**Comment by junichi11** [comment]
Ah, https://www.apache.org/legal/resolved.html#cc-sa , right?

The license is Creative Commons Attribution-ShareAlike 2.1 Japan (CC BY-SA 2.1 JP).
So, should we contact the Legal PMC?

**Comment by junichi11** [comment]
I've submitted it as a question: https://issues.apache.org/jira/browse/LEGAL-394

**Comment by matthiasblaesing** [comment]
@neilcsmith-net I read "imported" as "we take ownership". That would invalidate `CC-BY-SA`. I had to read three times to find the required license information (yeah I'm biased to latin letters and), but I think the "prominent label" is covered here.

The question to apache legal is reasonable, as `CC-BY` is explicitly white-listed while `CC-BY-SA` is not.

**Comment by junichi11** [comment]
@matthiasblaesing 
> I read "imported" as "we take ownership"

I see now. I just meant creating also the similar page on netbeans.apache.org. It doesn't mean moving/changing the ownership of NekoBean.  So Kazuko owns NekoBean. Sorry for my improper verb... I'll change the title of this PR.

BTW, I created this PR after Masaki reviewed these pages.

**Comment by matthiasblaesing** [comment]
@junichi11 no need to apologize, I just misunderstood :-)

**Comment by neilcsmith-net** [comment]
> The question to apache legal is reasonable, as CC-BY is explicitly white-listed while CC-BY-SA is not.

@matthiasblaesing it is explicitly covered (for unmodified media) in another section.  That whole page is also about Apache products rather than websites.

@junichi11 worth getting a legal viewpoint on the version, although note that CC licenses from v2 are always "or any later version" AFAIK.

**Comment by vieiro** [comment]
@junichi11 As far as I can tell this has been approved by legal. Maybe you want to add a link to the 2.0 version of the license (just in case, as legal requested, because the 2.1 version is only available in Japanesse, and the 2.0 version is also available in english).

After that I don't see a problem in you committing this request yourself, for the benefit of the many NetBeans users in Japan.

Thanks, @junichi11 !

**Comment by junichi11** [comment]
@vieiro Thank you for your help :) I asked [1] because I'm not sure whether we should add a link to the 2.0 version.

[1] https://issues.apache.org/jira/browse/LEGAL-394?focusedCommentId=16556945&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16556945

**Comment by geertjanw** [comment]
Any reason not to merge this?

**Comment by junichi11** [comment]
The author said, "I would like to avoid adding the link of the fan site". So I'm going to remove it on Sunday or later.

**Comment by junichi11** [comment]
@vieiro May I merge this?

**Comment by vieiro** [comment]
It would be a honor for us if you submitted this, @junichi11 . Thank you very much!

**Comment by junichi11** [comment]
It seems that the website is not updated. Am I wrong anything?

**Pull request merged**
