### PR TITLE
platform.netbeans.org resources

### PR DESCRIPTION
**Pull request by vieiro**
Some missing resources so that platform.netbeans.org works properly after the netbeans.org rerouting.

### CODE REVIEW

**Comment by GeertjanWielenga** [comment]
Awesome.

**Comment by vieiro** [comment]
Hi @geertjanw,
I think I'll add all these other resources at https://cwiki.apache.org/confluence/display/NETBEANS/netbeans.org+migration during the day.

**Comment by GeertjanWielenga** [comment]
Excellent. Also the DTDs, would be good.

**Comment by vieiro** [comment]
@geertjanw @JaroslavTulach DTDs will follow in another PR, as these require adding APLv2 license headers.

**Pull request merged**
