### PR TITLE
Another pass over HintsFileFormat

### PR DESCRIPTION
**Pull request by mbien**
Repaired a bullet point section and improved few other sections. 

Added more conditions to "Standard Conditions" with description.

### CODE REVIEW

**Comment by mbien** [comment]
@ebarboni do the pages support syntax highlighting for code sections?
https://netbeans.apache.org/jackpot/HintsFileFormat.html looks currently a bit boring.

**Comment by ebarboni** [comment]
I guess you need the  :syntax: true to have js associated with higlights

**Comment by mbien** [comment]
@ebarboni thanks. added a second commit with the syntax highlighting flags.

**Comment by mbien** [comment]
hmm. I managed to add a table of contents - thats cool but there is still no syntax highlighting. But its not so important.

https://netbeans.apache.org/jackpot/HintsFileFormat.html

**Comment by ebarboni** [comment]
mmm, my bad, I check that header was ok but js inclusion at the bottom only occurs on special template. Will refactor the scripts to have more consistency

**Comment by ebarboni** [comment]
mmmm again, PR created but java may not be the correct language to use make the code block fancy

**Comment by mbien** [comment]
@ebarboni yey there is color in the code! thanks!

**Pull request merged**
