### PR TITLE
link to mailing list thread about Java EE 8 support

### PR DESCRIPTION
**Pull request by pdurbin**
I looked for a JIRA issue about Java EE 8 support but I couldn't find one so I'm linking to @juneau001 's post on the mailing list. On Java Off Heap I heard him say he's working on Java EE 8 support. Thanks!!

### CODE REVIEW

**Comment by vieiro** [comment]
Looks ok to me. @geertjanw , @lkishalmi shall we merge?

**Comment by GeertjanWielenga** [comment]
Cool, makes sense.

**Comment by juneau001** [comment]
This will be helpful to those reading, thanks.

**Comment by pdurbin** [comment]
I'm glad everyone seems to be satisfied with the change. Since no one has mentioned a JIRA issue for Java EE 8 support, I assume there isn't one. If there is some other way to track the progress I'm happy to adjust this pull request to link to it. Thanks!

**Pull request merged**
