### PR TITLE
mavenized asciidoc checker

### PR DESCRIPTION
**Pull request by ebarboni**
A little tools to have some check.
I did not get it with gradle and don't want to pollute the site generation so I use maven to help looking for our websources. I'm not looking to change the build process.
It only read from the same sources and produce "audit" files.

got to tooling folder. 
mvn clean install (wait a bit)
go to netbeanswebsitescanner\target\audit 
NetBeansLinkMacro contains some link checkn with simple rules.

### CODE REVIEW

**Comment by mbien** [comment]
cool. This could also check for dead links, right?

**Comment by vieiro** [comment]
Should we store this in the netbeans-tools repo instead? Maybe we could enhance it to "render" asciidoc to html  and then get rid of JBake.

**Comment by ebarboni** [comment]
@mbien it only generate file (not well defined yet ) and we could use link checker to do the effective check

the current scanner allow every link starting with alphanumerical or / or "dot" that not very nice.
We could use xref for our links within the site. 

Was investigating a proposal: use XREF  all our file are asciidoc, we could move them to adoc extension and use the macro xref:mypage.adoc 
we could then use the "scanner" to detect every link starting with http://nebeans.apache.org or with alphanumerical and not ending with .adoc. Only working extension (asciidoc kind of untrusted)

After than we could add xref macro extension to check file actually there.

Advantage also you can navigate in github when you are reviewing on the real adoc file and the website is linking to html
#618 for implication and link to repository (clic [History section)
https://github.com/ebarboni/netbeans-website/blob/testgithub/netbeans.apache.org/src/content/about/index.adoc

PS:
I don't understand why the wiki page keep their extension on the live site.

@vieiro 
I prefer having the checker near the site (as we could have rules changes that are related to site). A bit like the https://github.com/apache/netbeans/blob/master/nbbuild/javadoctools/disallowed-links.xml in the main repo

I have no idea what would be the cost of removing jbake, but maybe doing all the build using maven instead gradle could be easier (but I'm mvn fan ) but this also implies website commiter to be fan

**Comment by ebarboni** [comment]
Lots of link target hurt asciidoc with [+ +] pattern, and some link: appears not parsed.
I continue on xref tasks

Some note:
as bits..../media is dead I was looking on screencast page @geertjanw 
https://netbeans.apache.org/kb/docs/intro-screencasts.html (section 7.4)
https://netbeans.apache.org/kb/docs/java/jdk8-nb74-screencast.html

**Comment by mbien** [comment]
do you want to use this from a CI job?

It could print its results with `::warning::` prefix for example. This would be automatically picked up by the workflow summary.
example is here:
https://github.com/apache/netbeans/blob/26514644711a26c08182ee21da9a622d5941eb64/.github/retry.sh#L24

**Comment by ebarboni** [comment]
Sorry to undiging  this conversation. I wonder if you know a way to gradelize that?  
I would say 
1. being able to build the "checker" 
2. duplicating the bake "section" to have thoose module checker in the classpath (not confilcting with main bake).

we now have gradlew clean build run
I would like to have gradlew clean check

**Comment by ebarboni** [comment]
this is no more "valid" basic test are done with help of antora

**Pull request closed without merging**
