### PR TITLE
Link colors / Header Sizes / Page Titles

### PR DESCRIPTION
**Pull request by vieiro**
- Links are magenta now (using same colors as in the logo), to differentiate them from headers.
- Using "Level 0" title as the title in the page (same as in tutorials).
- Redesigned some pages.
- More clear distinction between the download page and the features page.
- Changed fonts to "Open Sans".

NOTE: Please Squash & Merge.

### CODE REVIEW

**Comment by vieiro** [comment]
Sample screenshot of /download/index.html

captura de pantalla de 2019-02-09 10-28-12

**Comment by vieiro** [comment]
Added some buttons to the page! Clearer now?

**Comment by geertjanw** [comment]
Great, merge it, Yarda’s too. :-)

**Comment by JaroslavTulach** [comment]
I see blue and green buttons. Fine with me. Thanks.

**Pull request merged**
