### PR TITLE
Tutorials from the  3rd Oracle donation

### PR DESCRIPTION
**Pull request by vieiro**
In Asciidoc Format, automatically converted with incubator-netbeans-tools and with some minor enhancements (syntax highlighting, etc.).

### CODE REVIEW

**Comment by geertjanw** [comment]
Awesome!

**Comment by geertjanw** [comment]
Can this page https://netbeans.apache.org/help/index.html be seen as the future version of this page https://netbeans.org/kb/index.html ?

**Comment by vieiro** [comment]
No known reason not to merge. Squashing is probably a good idea.

I'd wait a little bit before allowing users to navigate to the tutorial. Let's think which tutorials we want to make visible and in which order (java, php, but not c++) and then let's start reviewing them to solve any issues. Automatic convertion saves lots of work, but there're some pages have some formatting errors (missing images that were not donated, etc.).

**Comment by geertjanw** [comment]
OK, excellent plan, squashing and merging now.

**Comment by calculuswhiz** [comment]
Apologies for the necropost. Some of the content [here](https://github.com/apache/netbeans-website/blame/master/netbeans.apache.org/src/content/kb/docs/java/debug-multithreaded.asciidoc) appears to be the same as the text here: https://stackoverflow.com/a/26960526. Is this from an archived tutorial somewhere? If so, would someone be able to say how old it is or where the archive can be found with original timestamps?

**Pull request merged**
