### PR TITLE
Trying to setup a location for updates, redirecting to the synergy VM…

### PR DESCRIPTION
**Pull request by jlahoda**
… for now.

### CODE REVIEW

**Comment by jkovalsky** [comment]
https://netbeans-vm.apache.org/uc/9.0/updates.xml.gz now exists. Please merge this pull request.

**Comment by vieiro** [comment]
https://netbeans.apache.org//nb/updates/9.0/updates.xml.gz seems to be working now.

**Comment by vieiro** [comment]
NOTE: HTTP 302 (moved temporarily) is better than HTTP 301 (moved permanently) in this case.
If we used 301 (moved permanently) clients might remember the permanent redirection, and we wouldn't get statistics for those.

**Comment by neilcsmith-net** [comment]
-1 to merging yet :smile:  OK, bit late.

The redirect should be to https on the VM, no?!

Would possibly be better as nb/9.0/updates ?  My thought was that anything specific to a version ends up under nb/9.x/ so that we can potentially do some simpler handling / redirects later.  Not too bothered on that one if we prefer this?

**Comment by vieiro** [comment]
Oh, well, AFAIK this is a temporary file for experiments in NETBEANS-330, subject to change.

**Comment by jkovalsky** [comment]
Status update: while downloading https://netbeans-vm.apache.org/uc/9.0/updates.xml.gz gets recorded to `/var/log/apache2/netbeans-vm_access.log` file, the redirected request from https://netbeans.apache.org/nb/updates/9.0/updates.xml.gz is not recorded.

**Comment by vieiro** [comment]
The requests to netbeans.apache.org will be logged in the netbeans.apache.org:/var/log/apache2 (probably), but we won't have access to this one, AFAIK. Infra may retrieve some statistics for us, though, on our request.

**Comment by neilcsmith-net** [comment]
@vieiro but surely there must be a way to log the redirected request on the VM too?  Long time since I've played with Apache, but that seems odd to me!

@jkovalsky does a request to http://netbeans-vm.apache.org/uc/9.0/updates.xml.gz get logged correctly?

**Comment by vieiro** [comment]
Maybe we should set up a RewriteLog [1], but I can't tell without looking at the server configuration. Maybe @jkovalsky wants to explain the current setup (private email may be better than posting here).

[1] https://serverfault.com/questions/10796/apache-where-to-examine-the-redirection-logs

**Comment by jkovalsky** [comment]
I confirm that requests for GZipped module catalog http://netbeans-vm.apache.org/uc/9.0/updates.xml.gz are recorded correctly from IDE:

`<%JSON:httpd_access%> { "time": "2018-05-15T12:23:40+0000", "clientip": "88.101.131.67", "duration": 131427, "status": 200, "request": "/uc/9.0/updates.xml.gz?unique=NB_CND_EXTIDE_GFMOD_GROOVY_JAVA_JC_MOB_PHP_WEBCOMMON_WEBEE096a88621-cef6-4ab9-ae6a-96772142ec5f_1dd774a0-d418-45fa-9fae-9fb4d222df8e", "uri": "/uc/9.0/updates.xml.gz", "remote_user": "-", "query_string": "?unique=NB_CND_EXTIDE_GFMOD_GROOVY_JAVA_JC_MOB_PHP_WEBCOMMON_WEBEE096a88621-cef6-4ab9-ae6a-96772142ec5f_1dd774a0-d418-45fa-9fae-9fb4d222df8e", "document": "/var/www/html/uc/9.0/updates.xml.gz", "bytes": 83682, "request_method": "GET", "referer": "-", "useragent": "NetBeans", "vhost": "netbeans-vm.apache.org", "geo_country": "-", "geo_long": "-", "geo_lat": "-", "geo_coords": "-,-", "geo_city": "-", "geo_combo": "-, -" }`

Besides, the puppet configuration for that VM is here: https://github.com/apache/infrastructure-puppet/blob/6a50871fb4e28a7876c787ff22aa5ee4ec4e54e9/data/nodes/netbeans-vm.apache.org.yaml

**Pull request merged**
