### PR TITLE
Updated 9.0 release notes 

### PR DESCRIPTION
**Pull request by emilianbold**

### CODE REVIEW

**Comment by geertjanw** [comment]
OK, merging.

**Comment by emilianbold** [comment]
So, this will automatically be mirrored in a while on netbeans.apache.org correct?

I'll send the announce emails when I see the new content.

**Comment by geertjanw** [comment]
It should. Sometimes it doesn't and Neil/Antonio do something manually. Before sending out announce e-mails, we need to check the mirrors IMHO.

**Comment by geertjanw** [comment]
This is where the mirrors for the final 9.0 are listed:

https://www.apache.org/dyn/closer.cgi/incubator/netbeans/incubating-netbeans-java/incubating-9.0

**Comment by geertjanw** [comment]
I can see your changes on GitHub but not reflected on the site:

https://github.com/apache/incubator-netbeans-website/blob/master/netbeans.apache.org/src/content/download/index.asciidoc

**Comment by emilianbold** [comment]
I see the generated HMTL on the asf-site branch https://github.com/apache/incubator-netbeans-website/blob/asf-site/content/download/nb90/nb90.html but I'm not certain when it syncs with the main site.

**Comment by geertjanw** [comment]
OK, I think we need help from Neil, who needs to tell us how we can fix it ourselves next time. I know it should sync automatically.

**Comment by neilcsmith-net** [comment]
Great!  Did it take time to sync or something not linked right / need fixing?

JFTR, if sync does fail it's probably something to ping infra about - at least that's what Antonio did last time.  You can check the website build task at https://builds.apache.org/view/Incubator%20Projects/job/incubator-netbeans-website/

And completely OT, but shouldn't there be another git tag added at the same commit for 9.0 now and linked to on that page?  The -vc suffixes were meant to be internal - seems weird to have that there.

Fantastic work! :smile:  Looking forward to working on updating my projects now.

**Comment by geertjanw** [comment]
Somehow it worked, either by itself, or Emilian did something.

**Comment by vieiro** [comment]
Sometimes the triggers don't work properly, and one has to manually force a synchronization, instructions here: http://mail-archives.apache.org/mod_mbox/netbeans-dev/201805.mbox/%3C5f23e0e3-be79-94bb-f4f9-3fa224029f04@vieiro.net%3E

**Comment by neilcsmith-net** [comment]
Ah, thanks @vieiro - I'd missed that post. Assumed there must be something.

**Comment by emilianbold** [comment]
> Somehow it worked, either by itself, or Emilian did something.

I forced a synchronization myself. Just took me a while to figure out it's needed and we have button for it.

**Pull request merged**
