### PR TITLE
[NETBEANS-429] Add the 'colorbox' jquery plugin, so images inside a '…

### PR DESCRIPTION
**Pull request by vieiro**
…feature' section are automatically enlarged when clicked.

'colorbox' is licensed under the MIT license
https://github.com/jackmoore/colorbox/blob/master/LICENSE.md

src/content/download/nb90/index.asciidoc contains an example of usage
when the document is in asciidoc format

### CODE REVIEW

**Comment by vieiro** [comment]
D'oh, I clicked the review button by accident :-/

**Comment by Chris2011** [comment]
Are there any other themes? The icons are definitely to small and not looking well with the flat design of the page.

**Comment by Chris2011** [comment]
And please keep in mind, that the last update was in november 2017 and the repo has a lot of open tickets.

**Comment by neilcsmith-net** [comment]
@Chris2011 Nov 2017? That's _years_ more up-to-date than I expected! :smile:

Note the thread on this we discussed this as a stopgap pending getting something more up-to-date / simpler in, possibly based on the Foundation stuff that is already there.

I agree with you on the icons.  Of the stock themes, only 3 and 5 have icons big enough on mobile from recollection (and don't have that horrible textured backdrop) - what do you think?

http://www.jacklmoore.com/colorbox/example3/
http://www.jacklmoore.com/colorbox/example5/

**Comment by Chris2011** [comment]
Yeah sure, nov 2017 is better than 2016 or so :D.

You mean on the coming weekend or on the last? I followed the discussion, yeah seems legit to me.

And yes, I feel the same about example 3 and five. Better than the rest. Sure better than nothing, but yes we should have a look whether foundation is the multi choice for our needs. Not to figure out which alternatives we have, if we have a full featured framework.


Cheers

Chris

**Comment by neilcsmith-net** [comment]
@Chris2011 - for the record, I disagree on reopening the discussion on Foundation, if that's what you mean?  I argued against it, but it's in there now and a lot of effort went into integrating it.  6 is at least a lot more modular and semantic than it was - there is work to be done in paring it down to just what we require though.

This PR is probably not the place for that discussion! :wink:

**Comment by Chris2011** [comment]
> possibly based on the Foundation stuff that is already there.

That was confusing me, because I thought you mean to find a combination.

**Comment by neilcsmith-net** [comment]
@Chris2011 ah, OK!  Foundation has modals but not a lightbox as such (at least as far as I can see) - should be simple enough to set something up on top of the modals.

**Pull request merged**
